#!/usr/bin/env bash

DIR=$(dirname "$(realpath "$0")")
FILES=$(ls "$DIR/dist/"*.js)

echo "| Item                           | minified (terser)     | minified + gzipped    |"
echo "|--------------------------------|-----------------------|-----------------------|"


for FILE in $FILES; do
  BASENAME=$(basename "$FILE" .js)
  MINIFIED="$DIR/dist/$BASENAME.js.min"
  ZIPPED="$DIR/dist/$BASENAME.js.gz"
  terser --module --rename "$FILE" >"$MINIFIED"
  gzip -c "$MINIFIED" >"$ZIPPED"

  PADDING=' '
  if [[ "$BASENAME" == 'scroll-snap-slider' ]]; then
    PADDING="\t"
  fi

  echo -e "| $BASENAME$PADDING\t | $(gstat --printf="%s" "$MINIFIED") B \t\t | $(gstat --printf="%s" "$ZIPPED") B \t\t |"

  rm "$MINIFIED"
  rm "$ZIPPED"
done

echo -e "\n"
