#!/usr/bin/env bash

tsc

FILES=$(ls ./dist/*.js)

echo "| Item                   | minified (terser)     | minified + gzipped    |"
echo "|------------------------|-----------------------|-----------------------|"


for FILE in $FILES; do
  BASENAME=$(basename "$FILE" .js)
  MINIFIED="./dist/$BASENAME.js.min"
  ZIPPED="./dist/$BASENAME.js.gz"
  terser --module --rename "$FILE" >"$MINIFIED"
  gzip -c "$MINIFIED" >"$ZIPPED"

  PADDING=' '
  if [[ "$BASENAME" == 'index' ]]; then
    PADDING="\t\t"
  fi

  echo -e "| $BASENAME$PADDING\t | $(stat --printf="%s" "$MINIFIED") B \t\t | $(stat --printf="%s" "$ZIPPED") B \t\t |"

  rm "$FILE"
  rm "dist/$BASENAME.d.ts"
  rm "$MINIFIED"
  rm "$ZIPPED"
done
