#!/usr/bin/env bash
# We want to use globs to pass multiple files
# shellcheck disable=SC2046
# shellcheck disable=SC2086
# SC2046 Quote this to prevent word splitting: https://github.com/koalaman/shellcheck/wiki/SC2046
# SC2086 Double quote to prevent globbing and word splitting: https://github.com/koalaman/shellcheck/wiki/SC2086

DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
source "$DIR/../node_modules/.bin/echolorized"

colored_output "$GREEN" "\n[EXECUTING PRE COMMIT HOOK]"

e_info "Removing Console Usage"

DIRECTORIES="src"

e_info "Linting & Fixing JS Code Style"
if ! eslint --fix $(find "$DIRECTORIES" -type f -name '*.js'); then
  e_error "JavaScript Error in JavaScript file. Run ${YELLOW}eslint src/**/*.js${RESET} to check."
  exit 1
fi

e_info "Linting & Fixing SCSS Code Style"
if ! stylelint --fix $(find "$DIRECTORIES" -type f -name '*.scss'); then
  e_error "Error in SCSS file. Run ${YELLOW}stylelint *.scss${RESET} to check."
  exit 1
fi

e_info "All good, staging additional changes.\n"
git update-index --again
